version: "3.8"

services:
  mariadb:
    image: mariadb:11.4
    container_name: nations-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: nations
      MARIADB_USER: nations_user
      MARIADB_PASSWORD: nations_pass
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
